name: PR Inference Checks

on:
  pull_request_target:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - "pyproject.toml"
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR Branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}  # This ensures checkout to the PR branch

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"  # Adjust based on your project

      - name: Install dependencies
        run: |
          pip install -e .
          pip install pytest
          pip install boto3==1.34.138
      - name: Run tests
        run: OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} pytest src/python_test/tests/
        