name: Dependabot Test Runner

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - "pyproject.toml"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Dependabot PR Branch
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"  # Adjust based on your project
      - name: Install dependencies
        run: |
          pip install -e .
          pip install pytest
      - name: Run tests
        run: pytest src/python_test/tests/
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
